services:
    web:
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./default.conf:/etc/nginx/conf.d/default.conf
          - ./.vitepress/dist:/usr/share/nginx/html
        ports:
          - "8080:80"

