services:
  mingle-docs:
    image: ghcr.io/ijpatricio/mingle-docs
    #ports: ["8080:80"] ## Uncomment this line if you want to expose the container to the host
    restart: always
    pull_policy: never
    networks: [web]

networks:
    web:
        external: true
